register(REPORT,
    id    = "TimelineContingency",
    name  = _("Timeline Contingency"),
    description =  _("Creates a timeline table for selected persons."),
    version = '1.0.5',
    gramps_target_version = "5.1",
    status = STABLE,
    fname = "timelinecontingency.py",
    authors = ["John R. Sibert"],
    authors_email = ["johnrsibert@gmail.com"],
    category = CATEGORY_TEXT,
    reportclass = "TimelineContingency",
    optionclass = "TimelineContingency",
    report_modes = [REPORT_MODE_CLI, REPORT_MODE_GUI, REPORT_MODE_BKI],
    require_active = False,
    )
